spring.jackson.serialization.INDENT_OUTPUT: true

logging.level:
  org.springframework: INFO
  io.undertow: INFO
  org.xnio: INFO
  org.apache: INFO
  org.hibernate: INFO
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
  address: 127.0.0.1

management.port: -1

spring:
  datasource:
    url: "jdbc:h2:mem:;DB_CLOSE_ON_EXIT=FALSE"

spring.jpa.hibernate.ddl-auto: create-drop
